EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';

EXPLAIN SELECT * FROM READERS WHERE LASTNAME = 'Kyio';

EXPLAIN SELECT * FROM BOOKS WHERE TITLE = 'THE HOME 2';

CREATE INDEX FIRSTNAMENO ON READERS (FIRSTNAME);
CREATE INDEX LASTNAMENO ON READERS (LASTNAME);
CREATE INDEX BOOKSNO ON BOOKS (TITLE);